CREATE TABLE IF NOT EXISTS breeds
(
    id         BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    label      VARCHAR(100) NOT NULL,
    species    ENUM ('CAT','DOG') NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- 시드: 테이블이 비어있을 때만 전체 삽입
-- 목록: 가나다순 정렬
INSERT INTO breeds (species, label, created_at, updated_at)
SELECT s.species, s.label, NOW(6), NOW(6)
FROM (
    SELECT 1 AS ord, 'DOG' AS species, '고든 세터' AS label
    UNION ALL SELECT 2, 'DOG', '골든 두들'
    UNION ALL SELECT 3, 'DOG', '골든 리트리버'
    UNION ALL SELECT 4, 'DOG', '그레이트 데인'
    UNION ALL SELECT 5, 'DOG', '그레이트 스위스 마운틴 도그'
    UNION ALL SELECT 6, 'DOG', '그레이트 피레니즈'
    UNION ALL SELECT 7, 'DOG', '그레이하운드'
    UNION ALL SELECT 8, 'DOG', '그로넨달'
    UNION ALL SELECT 9, 'DOG', '그리스 셰퍼드'
    UNION ALL SELECT 10, 'DOG', '그리스 헤어하운드'
    UNION ALL SELECT 11, 'DOG', '그린란드견'
    UNION ALL SELECT 12, 'DOG', '글렌 오브 이말 테리어'
    UNION ALL SELECT 13, 'DOG', '기슈견'
    UNION ALL SELECT 14, 'DOG', '꼬동 드 툴레아'
    UNION ALL SELECT 15, 'DOG', '나폴리탄 마스티프'
    UNION ALL SELECT 16, 'DOG', '노르보텐 스피츠'
    UNION ALL SELECT 17, 'DOG', '노르웨이안 룬트훈트'
    UNION ALL SELECT 18, 'DOG', '노르웨이안 버훈트'
    UNION ALL SELECT 19, 'DOG', '노르웨이안 엘크 하운드'
    UNION ALL SELECT 20, 'DOG', '노르위치 테리어'
    UNION ALL SELECT 21, 'DOG', '노바 스코셔 덕 톨링 리트리버'
    UNION ALL SELECT 22, 'DOG', '노포크 테리어'
    UNION ALL SELECT 23, 'DOG', '뉴펀들랜드'
    UNION ALL SELECT 24, 'DOG', '닥스훈트'
    UNION ALL SELECT 25, 'DOG', '달마시안'
    UNION ALL SELECT 26, 'DOG', '대니시 스웨디시 팜독'
    UNION ALL SELECT 27, 'DOG', '댄디 딘몬트 테리어'
    UNION ALL SELECT 28, 'DOG', '더치 셰퍼드'
    UNION ALL SELECT 29, 'DOG', '도고 아르헨티노'
    UNION ALL SELECT 30, 'DOG', '도그 드 보르도'
    UNION ALL SELECT 31, 'DOG', '도베르만'
    UNION ALL SELECT 32, 'DOG', '도사견'
    UNION ALL SELECT 33, 'DOG', '동경견 (경주개)'
    UNION ALL SELECT 34, 'DOG', '드레버'
    UNION ALL SELECT 35, 'DOG', '디어 하운드'
    UNION ALL SELECT 36, 'DOG', '라고토 로마뇰로'
    UNION ALL SELECT 37, 'DOG', '라사압소'
    UNION ALL SELECT 38, 'DOG', '라이카'
    UNION ALL SELECT 39, 'DOG', '라지 먼스터랜더'
    UNION ALL SELECT 40, 'DOG', '라케노이즈'
    UNION ALL SELECT 41, 'DOG', '라포니안 허더'
    UNION ALL SELECT 42, 'DOG', '래브라도 리트리버'
    UNION ALL SELECT 43, 'DOG', '랫 테리어'
    UNION ALL SELECT 44, 'DOG', '러셀 테리어'
    UNION ALL SELECT 45, 'DOG', '러스키 토이'
    UNION ALL SELECT 46, 'DOG', '러처'
    UNION ALL SELECT 47, 'DOG', '레드본 쿤하운드'
    UNION ALL SELECT 48, 'DOG', '레온베르거'
    UNION ALL SELECT 49, 'DOG', '레이크랜드 테리어'
    UNION ALL SELECT 50, 'DOG', '로디지안 리지백'
    UNION ALL SELECT 51, 'DOG', '로첸'
    UNION ALL SELECT 52, 'DOG', '로트와일러'
    UNION ALL SELECT 53, 'DOG', '루마니안 미오리틱 셰퍼드 독'
    UNION ALL SELECT 54, 'DOG', '리틀 라이언 독'
    UNION ALL SELECT 55, 'DOG', '마스티프'
    UNION ALL SELECT 56, 'DOG', '마운틴 커'
    UNION ALL SELECT 57, 'DOG', '말리노이즈'
    UNION ALL SELECT 58, 'DOG', '말티즈'
    UNION ALL SELECT 59, 'DOG', '말티푸'
    UNION ALL SELECT 60, 'DOG', '맨체스터 테리어'
    UNION ALL SELECT 61, 'DOG', '무디'
    UNION ALL SELECT 62, 'DOG', '미니어처 불 테리어'
    UNION ALL SELECT 63, 'DOG', '미니어처 슈나우저'
    UNION ALL SELECT 64, 'DOG', '미니어처 핀셔'
    UNION ALL SELECT 65, 'DOG', '미니어쳐 아메리칸 셰퍼드'
    UNION ALL SELECT 66, 'DOG', '바베트'
    UNION ALL SELECT 67, 'DOG', '바센지'
    UNION ALL SELECT 68, 'DOG', '바셋 포브 드 브레타뉴'
    UNION ALL SELECT 69, 'DOG', '바셋하운드'
    UNION ALL SELECT 70, 'DOG', '버거 피카드'
    UNION ALL SELECT 71, 'DOG', '버니즈 마운틴 독'
    UNION ALL SELECT 72, 'DOG', '베들링턴 테리어'
    UNION ALL SELECT 73, 'DOG', '벨지안 셰퍼드 독'
    UNION ALL SELECT 74, 'DOG', '보더 콜리'
    UNION ALL SELECT 75, 'DOG', '보더 테리어'
    UNION ALL SELECT 76, 'DOG', '보르도 마스티프'
    UNION ALL SELECT 77, 'DOG', '보르조이'
    UNION ALL SELECT 78, 'DOG', '보비에 드 플란더스'
    UNION ALL SELECT 79, 'DOG', '보스롱(뷰세런)'
    UNION ALL SELECT 80, 'DOG', '보스턴 테리어'
    UNION ALL SELECT 81, 'DOG', '보어보엘'
    UNION ALL SELECT 82, 'DOG', '보이킨 스패니얼'
    UNION ALL SELECT 83, 'DOG', '복서'
    UNION ALL SELECT 84, 'DOG', '볼로네즈'
    UNION ALL SELECT 85, 'DOG', '불 마스티프'
    UNION ALL SELECT 86, 'DOG', '불 테리어'
    UNION ALL SELECT 87, 'DOG', '불개'
    UNION ALL SELECT 88, 'DOG', '불도그'
    UNION ALL SELECT 89, 'DOG', '불리 쿠타'
    UNION ALL SELECT 90, 'DOG', '브라질리언 가드 독'
    UNION ALL SELECT 91, 'DOG', '브라코 이탈리아노'
    UNION ALL SELECT 92, 'DOG', '브라크 뒤 부르보네'
    UNION ALL SELECT 93, 'DOG', '브로홀머'
    UNION ALL SELECT 94, 'DOG', '브뤼셀 그리펀'
    UNION ALL SELECT 95, 'DOG', '브리어드'
    UNION ALL SELECT 96, 'DOG', '브리타니 스파니엘'
    UNION ALL SELECT 97, 'DOG', '블랙 러시안 테리어'
    UNION ALL SELECT 98, 'DOG', '블랙 앤 탄 쿤하운드'
    UNION ALL SELECT 99, 'DOG', '블러드 하운드'
    UNION ALL SELECT 100, 'DOG', '블루 피카르디 스패니얼'
    UNION ALL SELECT 101, 'DOG', '블루틱 쿤하운드'
    UNION ALL SELECT 102, 'DOG', '비글'
    UNION ALL SELECT 103, 'DOG', '비숑 프리제'
    UNION ALL SELECT 104, 'DOG', '비어디드 콜리'
    UNION ALL SELECT 105, 'DOG', '비즐라'
    UNION ALL SELECT 106, 'DOG', '쁘띠 바셋 그리펀 벤딘'
    UNION ALL SELECT 107, 'DOG', '쁘띠 브라바콘'
    UNION ALL SELECT 108, 'DOG', '사모예드'
    UNION ALL SELECT 109, 'DOG', '살루키'
    UNION ALL SELECT 110, 'DOG', '삽살개'
    UNION ALL SELECT 111, 'DOG', '샤를로스 울프독'
    UNION ALL SELECT 112, 'DOG', '샤페이'
    UNION ALL SELECT 113, 'DOG', '샤펜도스'
    UNION ALL SELECT 114, 'DOG', '서섹스 스패니얼'
    UNION ALL SELECT 115, 'DOG', '세인트 버나드'
    UNION ALL SELECT 116, 'DOG', '센트럴 아시안 오브차카'
    UNION ALL SELECT 117, 'DOG', '셔틀랜드 쉽독'
    UNION ALL SELECT 118, 'DOG', '소프트 코티드 휘튼 테리어'
    UNION ALL SELECT 119, 'DOG', '슈나우저'
    UNION ALL SELECT 120, 'DOG', '스무스 폭스 테리어'
    UNION ALL SELECT 121, 'DOG', '스웨디시 라프훈트'
    UNION ALL SELECT 122, 'DOG', '스위디쉬 발훈트'
    UNION ALL SELECT 123, 'DOG', '스카이 테리어'
    UNION ALL SELECT 124, 'DOG', '스코티시 디어하운드'
    UNION ALL SELECT 125, 'DOG', '스코티시 테리어'
    UNION ALL SELECT 126, 'DOG', '스키퍼키'
    UNION ALL SELECT 127, 'DOG', '스태포드셔 불 테리어'
    UNION ALL SELECT 128, 'DOG', '스탠다드 푸들'
    UNION ALL SELECT 129, 'DOG', '스테비훈'
    UNION ALL SELECT 130, 'DOG', '스패니쉬 그레이 하운드'
    UNION ALL SELECT 131, 'DOG', '스페니쉬 마스티프'
    UNION ALL SELECT 132, 'DOG', '스페니쉬 워터 독'
    UNION ALL SELECT 133, 'DOG', '스피노네 이달리아노'
    UNION ALL SELECT 134, 'DOG', '스피츠'
    UNION ALL SELECT 135, 'DOG', '슬로바키안 와이어헤어드 포인터'
    UNION ALL SELECT 136, 'DOG', '슬루기'
    UNION ALL SELECT 137, 'DOG', '시바견'
    UNION ALL SELECT 138, 'DOG', '시베리안 허스키'
    UNION ALL SELECT 139, 'DOG', '시추'
    UNION ALL SELECT 140, 'DOG', '시코쿠견'
    UNION ALL SELECT 141, 'DOG', '실리함 테리어'
    UNION ALL SELECT 142, 'DOG', '실키 테리어'
    UNION ALL SELECT 143, 'DOG', '아나톨리안 마스티프'
    UNION ALL SELECT 144, 'DOG', '아나톨리안 셰퍼드독'
    UNION ALL SELECT 145, 'DOG', '아메리칸 밴도지'
    UNION ALL SELECT 146, 'DOG', '아메리칸 불리'
    UNION ALL SELECT 147, 'DOG', '아메리칸 스태포드셔 테리어'
    UNION ALL SELECT 148, 'DOG', '아메리칸 스테그 하운드'
    UNION ALL SELECT 149, 'DOG', '아메리칸 아키타견'
    UNION ALL SELECT 150, 'DOG', '아메리칸 에스키모 독'
    UNION ALL SELECT 151, 'DOG', '아메리칸 워터 스패니얼'
    UNION ALL SELECT 152, 'DOG', '아메리칸 잉글리시 쿤하운드'
    UNION ALL SELECT 153, 'DOG', '아메리칸 코커 스파니엘'
    UNION ALL SELECT 154, 'DOG', '아메리칸 폭스하운드'
    UNION ALL SELECT 155, 'DOG', '아메리칸 헤어리스 테리어'
    UNION ALL SELECT 156, 'DOG', '아이리시 레드 앤 화이트 세터'
    UNION ALL SELECT 157, 'DOG', '아이리시 세터'
    UNION ALL SELECT 158, 'DOG', '아이리시 소프트코티드 휘튼 테리어'
    UNION ALL SELECT 159, 'DOG', '아이리시 울프 하운드'
    UNION ALL SELECT 160, 'DOG', '아이리시 워터 스패니얼'
    UNION ALL SELECT 161, 'DOG', '아이리시 테리어'
    UNION ALL SELECT 162, 'DOG', '아이슬랜딕 쉽독'
    UNION ALL SELECT 163, 'DOG', '아자와크'
    UNION ALL SELECT 164, 'DOG', '아크라이트'
    UNION ALL SELECT 165, 'DOG', '아크바시'
    UNION ALL SELECT 166, 'DOG', '아키타견'
    UNION ALL SELECT 167, 'DOG', '아펜첼러 제넨훈트'
    UNION ALL SELECT 168, 'DOG', '아펜핀셔'
    UNION ALL SELECT 169, 'DOG', '아프간 하운드'
    UNION ALL SELECT 170, 'DOG', '알래스칸 말라뮤트'
    UNION ALL SELECT 171, 'DOG', '알렌테조 마스티프'
    UNION ALL SELECT 172, 'DOG', '에스트렐라 마운틴 독'
    UNION ALL SELECT 173, 'DOG', '에어데일 테리어'
    UNION ALL SELECT 174, 'DOG', '엔틀버쳐 마운틴 독'
    UNION ALL SELECT 175, 'DOG', '오브차카'
    UNION ALL SELECT 176, 'DOG', '오스트레일리안 셰퍼드 독'
    UNION ALL SELECT 177, 'DOG', '오스트레일리안 캐틀 독'
    UNION ALL SELECT 178, 'DOG', '오스트레일리안 켈피'
    UNION ALL SELECT 179, 'DOG', '오스트레일리안 테리어'
    UNION ALL SELECT 180, 'DOG', '오터 하운드'
    UNION ALL SELECT 181, 'DOG', '올드 잉글리시 쉽독'
    UNION ALL SELECT 182, 'DOG', '와이마라너'
    UNION ALL SELECT 183, 'DOG', '와이어 폭스 테리어'
    UNION ALL SELECT 184, 'DOG', '와이어헤어드 비즐라'
    UNION ALL SELECT 185, 'DOG', '와이어헤어드 포인팅 그리폰'
    UNION ALL SELECT 186, 'DOG', '요크셔 테리어'
    UNION ALL SELECT 187, 'DOG', '요키'
    UNION ALL SELECT 188, 'DOG', '웨스트 하일랜드 화이트 테리어'
    UNION ALL SELECT 189, 'DOG', '웰시 스프링거 스파니엘'
    UNION ALL SELECT 190, 'DOG', '웰시 코기'
    UNION ALL SELECT 191, 'DOG', '웰시 코기 카디건'
    UNION ALL SELECT 192, 'DOG', '웰시 코기 펨브로크'
    UNION ALL SELECT 193, 'DOG', '웰시 테리어'
    UNION ALL SELECT 194, 'DOG', '유라시아'
    UNION ALL SELECT 195, 'DOG', '이비잔 하운드'
    UNION ALL SELECT 196, 'DOG', '이탈리안 그레이 하운드'
    UNION ALL SELECT 197, 'DOG', '이탈리안 세구죠'
    UNION ALL SELECT 198, 'DOG', '이탈리안 코로소 독'
    UNION ALL SELECT 199, 'DOG', '잉글리시 세터'
    UNION ALL SELECT 200, 'DOG', '잉글리시 스프링거 스패니얼'
    UNION ALL SELECT 201, 'DOG', '잉글리시 코카 스패니얼'
    UNION ALL SELECT 202, 'DOG', '잉글리시 폭스하운드'
    UNION ALL SELECT 203, 'DOG', '자이언트 슈나우저'
    UNION ALL SELECT 204, 'DOG', '재패니즈 친'
    UNION ALL SELECT 205, 'DOG', '잭 러셀 테리어'
    UNION ALL SELECT 206, 'DOG', '저먼 롱헤어드 포인터'
    UNION ALL SELECT 207, 'DOG', '저먼 셰퍼드 독'
    UNION ALL SELECT 208, 'DOG', '저먼 쇼트헤어드 포인터'
    UNION ALL SELECT 209, 'DOG', '저먼 스피츠'
    UNION ALL SELECT 210, 'DOG', '저먼 와이어헤어드 포인터'
    UNION ALL SELECT 211, 'DOG', '저먼 핀셔'
    UNION ALL SELECT 212, 'DOG', '저먼 헌팅 테리어'
    UNION ALL SELECT 213, 'DOG', '제주개'
    UNION ALL SELECT 214, 'DOG', '제패니즈 스피츠'
    UNION ALL SELECT 215, 'DOG', '진돗개'
    UNION ALL SELECT 216, 'DOG', '차우차우'
    UNION ALL SELECT 217, 'DOG', '차이니스 크레스티드'
    UNION ALL SELECT 218, 'DOG', '체서피크 베이 리트리버'
    UNION ALL SELECT 219, 'DOG', '체스키 테리어'
    UNION ALL SELECT 220, 'DOG', '체코슬로바키안 울프독'
    UNION ALL SELECT 221, 'DOG', '치누크'
    UNION ALL SELECT 222, 'DOG', '치와와'
    UNION ALL SELECT 223, 'DOG', '카네 코르소'
    UNION ALL SELECT 224, 'DOG', '카렐리안 베어 독'
    UNION ALL SELECT 225, 'DOG', '카발리에 킹 찰스 스패니얼'
    UNION ALL SELECT 226, 'DOG', '카이견'
    UNION ALL SELECT 227, 'DOG', '카타호울라 레오파트 독'
    UNION ALL SELECT 228, 'DOG', '캉갈'
    UNION ALL SELECT 229, 'DOG', '캐롤리나 독'
    UNION ALL SELECT 230, 'DOG', '컬리 코티드 리트리버'
    UNION ALL SELECT 231, 'DOG', '케니스펜더'
    UNION ALL SELECT 232, 'DOG', '케리 블루 테리어'
    UNION ALL SELECT 233, 'DOG', '케언 테리어'
    UNION ALL SELECT 234, 'DOG', '케이넌 독'
    UNION ALL SELECT 235, 'DOG', '케이스혼트'
    UNION ALL SELECT 236, 'DOG', '코리안 마스티프'
    UNION ALL SELECT 237, 'DOG', '코몬도르'
    UNION ALL SELECT 238, 'DOG', '코카 스파니엘'
    UNION ALL SELECT 239, 'DOG', '코카시언 셰퍼드 독'
    UNION ALL SELECT 240, 'DOG', '콜리'
    UNION ALL SELECT 241, 'DOG', '콜리 (러프)'
    UNION ALL SELECT 242, 'DOG', '콜리 (스무스)'
    UNION ALL SELECT 243, 'DOG', '쿠바츠'
    UNION ALL SELECT 244, 'DOG', '크레타 하운드'
    UNION ALL SELECT 245, 'DOG', '크로아티안 쉽독'
    UNION ALL SELECT 246, 'DOG', '클럼버 스패니얼'
    UNION ALL SELECT 247, 'DOG', '킹 찰스 스파니엘'
    UNION ALL SELECT 248, 'DOG', '타이 리지백 독'
    UNION ALL SELECT 249, 'DOG', '타이완 독(포르모산 마운틴 도그)'
    UNION ALL SELECT 250, 'DOG', '테디 루즈벨트 테리어'
    UNION ALL SELECT 251, 'DOG', '테르뷰렌'
    UNION ALL SELECT 252, 'DOG', '토른쟈크'
    UNION ALL SELECT 253, 'DOG', '토이 맨체스터 테리어'
    UNION ALL SELECT 254, 'DOG', '토이 폭스 테리어'
    UNION ALL SELECT 255, 'DOG', '통일개'
    UNION ALL SELECT 256, 'DOG', '트라이 하운드'
    UNION ALL SELECT 257, 'DOG', '트랜시바니안 하운드'
    UNION ALL SELECT 258, 'DOG', '트리잉 워커 쿤하운드'
    UNION ALL SELECT 259, 'DOG', '트리잉 테네시 브린들'
    UNION ALL SELECT 260, 'DOG', '티베탄 마스티프'
    UNION ALL SELECT 261, 'DOG', '티베탄 스패니얼'
    UNION ALL SELECT 262, 'DOG', '티베탄 테리어'
    UNION ALL SELECT 263, 'DOG', '파라오 하운드'
    UNION ALL SELECT 264, 'DOG', '파슨 러셀 테리어'
    UNION ALL SELECT 265, 'DOG', '파피용'
    UNION ALL SELECT 266, 'DOG', '패터데일 테리어'
    UNION ALL SELECT 267, 'DOG', '퍼그'
    UNION ALL SELECT 268, 'DOG', '페키니즈'
    UNION ALL SELECT 269, 'DOG', '포르셀엔'
    UNION ALL SELECT 270, 'DOG', '포르투갈 워터 독'
    UNION ALL SELECT 271, 'DOG', '포르투갈 포덴고'
    UNION ALL SELECT 272, 'DOG', '포르투갈 포인터'
    UNION ALL SELECT 273, 'DOG', '포메라니안'
    UNION ALL SELECT 274, 'DOG', '포인터'
    UNION ALL SELECT 275, 'DOG', '폭스 테리어'
    UNION ALL SELECT 276, 'DOG', '폴리시 로랜드 쉽독'
    UNION ALL SELECT 277, 'DOG', '폼피츠'
    UNION ALL SELECT 278, 'DOG', '푸델포인터'
    UNION ALL SELECT 279, 'DOG', '푸들'
    UNION ALL SELECT 280, 'DOG', '푸미'
    UNION ALL SELECT 281, 'DOG', '풀리'
    UNION ALL SELECT 282, 'DOG', '풍산개'
    UNION ALL SELECT 283, 'DOG', '프레사 카나리오'
    UNION ALL SELECT 284, 'DOG', '프렌치 불독'
    UNION ALL SELECT 285, 'DOG', '프렌치 스패니얼'
    UNION ALL SELECT 286, 'DOG', '플랫 코티드 리트리버'
    UNION ALL SELECT 287, 'DOG', '피니시 라프훈트'
    UNION ALL SELECT 288, 'DOG', '피니시 스피츠'
    UNION ALL SELECT 289, 'DOG', '피레니안 셰퍼드'
    UNION ALL SELECT 290, 'DOG', '필드 스패니얼'
    UNION ALL SELECT 291, 'DOG', '필라 브라질레이로'
    UNION ALL SELECT 292, 'DOG', '핏 불 테리어'
    UNION ALL SELECT 293, 'DOG', '하바니즈(하바네제)'
    UNION ALL SELECT 294, 'DOG', '해리어'
    UNION ALL SELECT 295, 'DOG', '호바와트'
    UNION ALL SELECT 296, 'DOG', '홋카이도견'
    UNION ALL SELECT 297, 'DOG', '휘핏'
    UNION ALL SELECT 298, 'DOG', '세상에 하나뿐인 믹스'
    UNION ALL SELECT 299, 'DOG', '기타'
    UNION ALL SELECT 300, 'CAT', '네벨룽'
    UNION ALL SELECT 301, 'CAT', '노르웨이 숲고양이'
    UNION ALL SELECT 302, 'CAT', '데본 렉스'
    UNION ALL SELECT 303, 'CAT', '돈스코이'
    UNION ALL SELECT 304, 'CAT', '라가머핀'
    UNION ALL SELECT 305, 'CAT', '라이코이'
    UNION ALL SELECT 306, 'CAT', '라팜'
    UNION ALL SELECT 307, 'CAT', '라팜 숏헤어'
    UNION ALL SELECT 308, 'CAT', '랙돌'
    UNION ALL SELECT 309, 'CAT', '러시안 블루'
    UNION ALL SELECT 310, 'CAT', '맹크스'
    UNION ALL SELECT 311, 'CAT', '먼치킨'
    UNION ALL SELECT 312, 'CAT', '먼치킨 롱헤어'
    UNION ALL SELECT 313, 'CAT', '메인쿤'
    UNION ALL SELECT 314, 'CAT', '미뉴엣 (나폴레옹)'
    UNION ALL SELECT 315, 'CAT', '미뉴엣 롱헤어'
    UNION ALL SELECT 316, 'CAT', '민스킨'
    UNION ALL SELECT 317, 'CAT', '발리니즈'
    UNION ALL SELECT 318, 'CAT', '버만'
    UNION ALL SELECT 319, 'CAT', '버미즈'
    UNION ALL SELECT 320, 'CAT', '버밀라'
    UNION ALL SELECT 321, 'CAT', '벵갈'
    UNION ALL SELECT 322, 'CAT', '봄베이'
    UNION ALL SELECT 323, 'CAT', '브라질리안 숏헤어'
    UNION ALL SELECT 324, 'CAT', '브리티시 롱헤어'
    UNION ALL SELECT 325, 'CAT', '브리티시 숏헤어'
    UNION ALL SELECT 326, 'CAT', '사바나'
    UNION ALL SELECT 327, 'CAT', '샤트룩스'
    UNION ALL SELECT 328, 'CAT', '샴'
    UNION ALL SELECT 329, 'CAT', '세렝게티'
    UNION ALL SELECT 330, 'CAT', '셀커크 렉스'
    UNION ALL SELECT 331, 'CAT', '셀커크 렉스 롱헤어'
    UNION ALL SELECT 332, 'CAT', '소말리'
    UNION ALL SELECT 333, 'CAT', '소코케'
    UNION ALL SELECT 334, 'CAT', '스노우 슈'
    UNION ALL SELECT 335, 'CAT', '스코티시 스트레이트'
    UNION ALL SELECT 336, 'CAT', '스코티시 폴드'
    UNION ALL SELECT 337, 'CAT', '스코티시 폴드 롱헤어'
    UNION ALL SELECT 338, 'CAT', '스키프 토이 밥테일'
    UNION ALL SELECT 339, 'CAT', '스핑크스'
    UNION ALL SELECT 340, 'CAT', '시베리안 고양이'
    UNION ALL SELECT 341, 'CAT', '싱가푸라'
    UNION ALL SELECT 342, 'CAT', '싸이프러스 아프로디테'
    UNION ALL SELECT 343, 'CAT', '아라비안 마우'
    UNION ALL SELECT 344, 'CAT', '아메리칸 밥테일'
    UNION ALL SELECT 345, 'CAT', '아메리칸 밥테일 숏헤어'
    UNION ALL SELECT 346, 'CAT', '아메리칸 숏헤어'
    UNION ALL SELECT 347, 'CAT', '아메리칸 와이어헤어'
    UNION ALL SELECT 348, 'CAT', '아메리칸 컬'
    UNION ALL SELECT 349, 'CAT', '아비시니안'
    UNION ALL SELECT 350, 'CAT', '엑조틱 숏헤어'
    UNION ALL SELECT 351, 'CAT', '오리엔탈 고양이'
    UNION ALL SELECT 352, 'CAT', '오스트레일리안 미스트'
    UNION ALL SELECT 353, 'CAT', '오시캣'
    UNION ALL SELECT 354, 'CAT', '오호스 아즐레스'
    UNION ALL SELECT 355, 'CAT', '오호스 아즐레스 롱헤어'
    UNION ALL SELECT 356, 'CAT', '요크 초콜릿'
    UNION ALL SELECT 357, 'CAT', '유러피안 버미즈'
    UNION ALL SELECT 358, 'CAT', '유러피안 숏헤어'
    UNION ALL SELECT 359, 'CAT', '이집션 마우'
    UNION ALL SELECT 360, 'CAT', '자바니즈'
    UNION ALL SELECT 361, 'CAT', '재패니즈 밥테일'
    UNION ALL SELECT 362, 'CAT', '저먼 렉스'
    UNION ALL SELECT 363, 'CAT', '쵸시'
    UNION ALL SELECT 364, 'CAT', '카오마니'
    UNION ALL SELECT 365, 'CAT', '캘리포니아 스팽글드'
    UNION ALL SELECT 366, 'CAT', '컬러포인트 숏헤어'
    UNION ALL SELECT 367, 'CAT', '코니시 렉스'
    UNION ALL SELECT 368, 'CAT', '코랏'
    UNION ALL SELECT 369, 'CAT', '코리안 숏헤어'
    UNION ALL SELECT 370, 'CAT', '쿠리리안 밥테일'
    UNION ALL SELECT 371, 'CAT', '킴릭'
    UNION ALL SELECT 372, 'CAT', '타이'
    UNION ALL SELECT 373, 'CAT', '터키시 앙고라'
    UNION ALL SELECT 374, 'CAT', '터키시반'
    UNION ALL SELECT 375, 'CAT', '토이거'
    UNION ALL SELECT 376, 'CAT', '통키니즈'
    UNION ALL SELECT 377, 'CAT', '페르시안'
    UNION ALL SELECT 378, 'CAT', '피터볼드'
    UNION ALL SELECT 379, 'CAT', '픽시 밥'
    UNION ALL SELECT 380, 'CAT', '픽시 밥 롱헤어'
    UNION ALL SELECT 381, 'CAT', '하바나 브라운'
    UNION ALL SELECT 382, 'CAT', '하이랜더'
    UNION ALL SELECT 383, 'CAT', '하이랜드 폴드'
    UNION ALL SELECT 384, 'CAT', '히말라얀'
    UNION ALL SELECT 385, 'CAT', '세상에 하나뿐인 믹스'
    UNION ALL SELECT 386, 'CAT', '기타'
) s
WHERE NOT EXISTS (SELECT 1 FROM breeds)
ORDER BY s.ord;
